# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A function assign ranks to data
#' @description A function assign ranks to data
#' @param xs data to be assigned with rank
#' @return Rank vector of input data 
#' @export
rankdata <- function(xs) {
    .Call(`_BA22022002_rankdata`, xs)
}

